#!/bin/bash

../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 0 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 1 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 2 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 3 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 4 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 5 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 6 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 7 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 8 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 9 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 10 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 11 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 12 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 13 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 14 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 15 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 16 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 17 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 18 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 19 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 20 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 21 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 22 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 23 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 24 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 25 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 26 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 27 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 28 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 29 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 30 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 31 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 32 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 33 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 34 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 35 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 36 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 37 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 38 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 39 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 40 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 41 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 42 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 43 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 44 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 45 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 46 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 47 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 48 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 49 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 50 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 51 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 52 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 53 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 54 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 55 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 56 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 57 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 58 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 59 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 60 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 61 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 62 &
../../../../../BUILD2/setup_environment.sh python modeling_enumerate_multi.py 45000 63 &

